iter5
landrushka/monitor pull request #5
Opened 2023-10-17 13:17 UTC by landrushka

iter5

2023-10-18 15:47 UTC, capsulated requested changes
В принципе, всё круто, только спрятать бы объекты, связанные с метриками из `cmd` в `internal` (написал в коментах)

2023-10-18 15:47 UTC, capsulated commented on cmd/agent/agent.go
> +type statsFloat map[string]float64
❌ Не очень хорошая история объекты внутренней реализации описывать непосредственно в `cmd`. Лучше для них специальный пакет создать. Для конфига - это ещё ок, а для метрик и т.п. лучше "спрятать"

2023-10-18 15:47 UTC, capsulated commented on internal/handlers/handlers.go
> +func (bh *Handler) UpdateHandle(rw http.ResponseWriter, r *http.Request) {
А почeму `bh`? 🤔

2023-10-20 17:53 UTC, landrushka commented on internal/handlers/handlers.go
> +func (bh *Handler) UpdateHandle(rw http.ResponseWriter, r *http.Request) {
Я сначала обозвал тип BaseHandler, а потом переделывал и забыл про обозначение этой переменной)

2023-10-23 09:41 UTC, capsulated commented on internal/handlers/handlers.go
> +func (bh *Handler) UpdateHandle(rw http.ResponseWriter, r *http.Request) {
> Я сначала обозвал тип BaseHandler, а потом переделывал и забыл про обозначение этой переменной)

Ааа ясно)

2023-10-23 09:50 UTC, capsulated requested changes
❌ Так и остались объекты для статы в cmd 😫

Создай, плиз, отдельный(е) пакеты для них в internal. Что-то типа папки metrics и там типы с методами для сбора метрик.

А в cmd только инизиализация (парсинг конфигов и создание экземпляров) и запуск этих воркеров.

И будет идеально

2023-10-23 09:50 UTC, capsulated commented on cmd/agent/agent.go
> +type statsInt storage.StatsInt
❌ Так и остались объекты для статы в `cmd` 😫

Создай, плиз, отдельный(е) пакеты для них в `internal`. Что-то типа папки `metrics` и там типы с методами для сбора метрик.

А в  `cmd` только инизиализация (парсинг конфигов и создание экземпляров) и запуск этих воркеров.

И будет идеально

2023-10-23 19:27 UTC, capsulated approved these changes
Всё равно осталась логика метрик внутри `cmd` main() - её там быть не должно. Вызова запросов внутри также, не должно быть в main(). Запуск и работу воркера нужно инкапсулировать в метод запуска и положить в пакет.

Сейчас работу принимаю, но в следующем спринте не приму, если логика сборщика метрик останется в cmd в main

2023-10-24 17:29 UTC, merged